version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      # Host + Webhook
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678

      # Timezone
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh

      # Enforce file permission
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      # Enable runners
      - N8N_RUNNERS_ENABLED=true

    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always
